nohup: ignoring input
Traceback (most recent call last):
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fastapi-assignment-1-RG-_jVMF-py3.12/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fastapi-assignment-1-RG-_jVMF-py3.12/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fastapi-assignment-1-RG-_jVMF-py3.12/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fastapi-assignment-1-RG-_jVMF-py3.12/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fastapi-assignment-1-RG-_jVMF-py3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fastapi-assignment-1-RG-_jVMF-py3.12/lib/python3.12/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fastapi-assignment-1-RG-_jVMF-py3.12/lib/python3.12/site-packages/uvicorn/main.py", line 577, in run
    server.run()
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fastapi-assignment-1-RG-_jVMF-py3.12/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fastapi-assignment-1-RG-_jVMF-py3.12/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fastapi-assignment-1-RG-_jVMF-py3.12/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fastapi-assignment-1-RG-_jVMF-py3.12/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fastapi-assignment-1-RG-_jVMF-py3.12/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/22-5-team5-server/wastory/main.py", line 6, in <module>
    from wastory.api import api_router
  File "/home/ubuntu/22-5-team5-server/wastory/api.py", line 3, in <module>
    from wastory.app.user.views import user_router
  File "/home/ubuntu/22-5-team5-server/wastory/app/user/views.py", line 11, in <module>
    from wastory.app.user.service import UserService
  File "/home/ubuntu/22-5-team5-server/wastory/app/user/service.py", line 14, in <module>
    from wastory.app.user.store import UserStore
  File "/home/ubuntu/22-5-team5-server/wastory/app/user/store.py", line 10, in <module>
    from wastory.database.annotation import transactional
  File "/home/ubuntu/22-5-team5-server/wastory/database/annotation.py", line 1, in <module>
    from wastory.database.connection import SESSION, reset_session, start_new_session_if_not_exists
  File "/home/ubuntu/22-5-team5-server/wastory/database/connection.py", line 61, in <module>
    session_factory=DatabaseManager().session_factory, scopefunc=get_session_id
                    ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/22-5-team5-server/wastory/database/connection.py", line 18, in __init__
    self.engine = create_async_engine(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fastapi-assignment-1-RG-_jVMF-py3.12/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 120, in create_async_engine
    sync_engine = _create_engine(url, **kw)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fastapi-assignment-1-RG-_jVMF-py3.12/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fastapi-assignment-1-RG-_jVMF-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 550, in create_engine
    entrypoint = u._get_entrypoint()
                 ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fastapi-assignment-1-RG-_jVMF-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 758, in _get_entrypoint
    cls = registry.load(name)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fastapi-assignment-1-RG-_jVMF-py3.12/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 375, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:.
